package com.hospital_manager.controllers.commands;

public enum CommandNames {

    LOGIN,
    LOGOUT,
    ADD_ACCOUNT,
    REGISTRATION,
    ADD_DIAGNOSIS,
    CHANGE_LOCALE,
    GO_TO_INDEX_PAGE,
    ADD_APPOINTMENT,
    GO_TO_PROFILE_PAGE,
    GO_TO_ADD_STAFF_PAGE,
    GO_TO_MAIN_PAGE,
    GO_TO_DIAGNOSIS_PAGE,
    ADD_ADDITIONAL_INFO,
    ADD_PATIENTS_TO_DOCTOR,
    UPDATE_PASSWORD,
    GO_TO_ADD_ADDITIONAL_INFO_PAGE,
    GO_TO_PASSWORD_UPDATE_PAGE,
    GO_TO_RECEIPT_DATE_PAGE,
    SUBMIT_APPLICATION,
    GO_TO_FREE_PATIENTS_PAGE,
    GO_TO_MEDICAL_HISTORY_PAGE,
    GO_TO_ADD_APPOINTMENT_PAGE,
    GO_TO_DOCTORS_PATIENTS_PAGE,
    UPDATE_APPOINTMENT_STATUS,
    GO_TO_ADD_APPOINTMENT_NEXT_PAGE,
    GO_TO_STAFF_APPOINTMENT_LIST_PAGE,
    GO_TO_PATIENT_APPOINTMENT_LIST_PAGE

}
